using Keysharp.Runtime;

namespace Keysharp.Builtins
{
	internal interface I__Enum
	{
		public KeysharpFunc __Enum(object count);
	}

	/// <summary>
	/// The base class of every script object. The C# type is named <c>KeysharpObject</c> because
	/// <c>Object</c> is <see cref="System.Object"/>; scripts see it as <c>Object</c> via
	/// <see cref="UserDeclaredNameAttribute"/>.
	/// </summary>
	[UserDeclaredName("Object")]
	public class KeysharpObject : Any
	{
		public KeysharpObject(params object[] args) : base(args) { }

		/// <summary>
		/// Creates a new <see cref="KeysharpObject"/> object.
		/// This can be called manually by the script or be generated by the parser
		/// for object literal construction like:
		/// val := { one : 1 }
		/// Note that the map must be case insensitive so that property lookups like:
		/// val.one and val.One both work.
		/// </summary>
		/// <param name="args">The optional data to initialize the <see cref="KeysharpObject"/> with. This can be:
		///     An object[] of key,value pairs.
		/// </param>
		/// <returns>A new <see cref="KeysharpObject"/> object.</returns>
		public static object staticCall(object @this, params object[] args)
		{
			if (@this is not Class cls)
				return Errors.TypeErrorOccurred(@this, typeof(Class));

			var kso = cls.Call(args) as KeysharpObject;
			if (kso.type != typeof(KeysharpObject))
				return kso;

			var count = (args.Length / 2) * 2;

			for (var i = 0; i < count; i += 2)
			{
				var name = args[i].ToString();
				if (name.Equals("base", StringComparison.OrdinalIgnoreCase))
					kso.SetBaseInternal((Any)args[i + 1]);
				else
					kso.DefinePropInternal(name, new OwnPropsDesc(kso, args[i + 1]));
			}
			return kso;
		}

		/// <summary>
		/// Return a cloned copy of the object.
		/// Just calling MemberwiseClone() is sufficient to clone all of the properties as well
		/// as the OwnProps object op.
		/// </summary>
		/// <returns>A cloned copy of the object.</returns>
		public new object Clone()
		{
			return MemberwiseClone();
		}

		public static object DefineProp(object @this, object name, object descriptor) => Objects.DefineProp(@this, name, descriptor);

		public static object DeleteProp(object @this, object name) => (@this as Any).DeleteOwnPropInternal(name.As());

		public static object GetOwnPropDesc(object @this, object name)
		{
			var nameVal = name.As();
			var obj = @this as Any;

			if (obj.op != null && obj.op.TryGetValue(nameVal, out var dynProp))
			{
				return dynProp.GetDesc();
			}

			try
			{
				var val = Script.GetPropertyValue(obj, nameVal);
				return KeysharpObject.staticCall(TheScript.Vars.Statics[typeof(KeysharpObject)], ["value", val]);
			}
			catch
			{
			}

			return Script.CompatReturnsUnsetForMissing ? null
				: Errors.PropertyErrorOccurred($"Object did not have an OwnProp named {nameVal}.");
		}

		public static object __Ref(object @this, object name, params object[] args)
		{
			var ctorArgs = new object[(args?.Length ?? 0) + 2];
			ctorArgs[0] = @this;
			ctorArgs[1] = name;
			if (args != null && args.Length > 0)
				System.Array.Copy(args, 0, ctorArgs, 2, args.Length);
			return PropRef.staticCall(TheScript.Vars.Statics[typeof(PropRef)], ctorArgs);
		}

		public static long HasOwnProp(object @this, object name)
		{
			var obj = @this as Any;
			var nameVal = name.As();

			if (obj.op != null && obj.op.ContainsKey(nameVal))
				return 1L;

			return Reflections.FindOwnProp(obj.GetType(), nameVal) ? 1L : 0L;
		}

		public static long OwnPropCount(object @this)
		{
			var obj = @this as Any;
			var ct = 0L;
			var type = obj.GetType();
			var isMapOnly = type == typeof(Map);

			if (obj.op != null)
				ct += obj.op.Count;

			if (!isMapOnly)
			{
				_ = Reflections.FindAndCacheProperty(type, "", -1);
				ct += Reflections.OwnPropCount(type);
			}

			return ct;
		}

		public static object OwnProps(object @this, object getValues = null)
		{
			var obj = @this as Any;
			var vals = getValues.Ab(true);
			var props = new Dictionary<object, object>();

			if (obj.op != null)
			{
				foreach (var kv in obj.op)
				{
					if (kv.Key == "__Static") //This throws if the value is tried to access because "this" is passed
						continue;

					props[kv.Key] = kv.Value;
				}
			}

			return OwnPropsEnumeration.CreateEnumerator(obj, props, vals);
		}

		[PublicHiddenFromUser]
		public override Any Base
		{
			get => _base;
			set => Objects.ObjSetBase(this, value);
		}
	}
}
