//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Keysharp.Core/Parsing/Antlr/PreprocessorParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Keysharp.Parsing.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class PreprocessorParser : PreprocessorParserBase {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		DerefStart=1, DerefEnd=2, ObjectLiteralStart=3, ObjectLiteralEnd=4, ConcatDot=5, 
		Maybe=6, SingleLineBlockComment=7, SingleLineComment=8, HotstringTrigger=9, 
		RemapKey=10, HotkeyTrigger=11, OpenBracket=12, CloseBracket=13, OpenParen=14, 
		CloseParen=15, OpenBrace=16, CloseBrace=17, Comma=18, Assign=19, QuestionMark=20, 
		QuestionMarkDot=21, Colon=22, DoubleColon=23, Ellipsis=24, Dot=25, PlusPlus=26, 
		MinusMinus=27, Plus=28, Minus=29, BitNot=30, Not=31, Multiply=32, Divide=33, 
		IntegerDivide=34, Modulus=35, Power=36, NullCoalesce=37, Hashtag=38, RightShiftArithmetic=39, 
		LeftShiftArithmetic=40, RightShiftLogical=41, LessThan=42, MoreThan=43, 
		LessThanEquals=44, GreaterThanEquals=45, Equals_=46, NotEquals=47, IdentityEquals=48, 
		IdentityNotEquals=49, RegExMatch=50, BitAnd=51, BitXOr=52, BitOr=53, And=54, 
		Or=55, MultiplyAssign=56, DivideAssign=57, ModulusAssign=58, PlusAssign=59, 
		MinusAssign=60, LeftShiftArithmeticAssign=61, RightShiftArithmeticAssign=62, 
		RightShiftLogicalAssign=63, IntegerDivideAssign=64, ConcatenateAssign=65, 
		BitAndAssign=66, BitXorAssign=67, BitOrAssign=68, PowerAssign=69, NullishCoalescingAssign=70, 
		Arrow=71, NullLiteral=72, Unset=73, True=74, False=75, DecimalLiteral=76, 
		HexIntegerLiteral=77, OctalIntegerLiteral=78, OctalIntegerLiteral2=79, 
		BinaryIntegerLiteral=80, BigHexIntegerLiteral=81, BigOctalIntegerLiteral=82, 
		BigBinaryIntegerLiteral=83, BigDecimalIntegerLiteral=84, Break=85, Do=86, 
		Instanceof=87, Switch=88, Case=89, Default=90, Else=91, Catch=92, Finally=93, 
		Return=94, Continue=95, For=96, While=97, Parse=98, Reg=99, Read=100, 
		Files=101, Loop=102, Until=103, This=104, If=105, Throw=106, Delete=107, 
		In=108, Try=109, Yield=110, Is=111, Contains=112, VerbalAnd=113, VerbalNot=114, 
		VerbalOr=115, Goto=116, Get=117, Set=118, Class=119, Enum=120, Extends=121, 
		Super=122, Base=123, Export=124, Import=125, From=126, As=127, Async=128, 
		Await=129, Static=130, Global=131, Local=132, Identifier=133, ContinuationSection=134, 
		StringLiteral=135, EOL=136, WS=137, UnexpectedCharacter=138, StringLiteralPart=139, 
		StringModeTerminator=140, StringModeTrivia=141, StringModeContinuationSection=142, 
		HotstringExpansion=143, Digits=144, HotIf=145, InputLevel=146, SuspendExempt=147, 
		UseHook=148, Hotstring=149, Module=150, Define=151, Undef=152, ElIf=153, 
		EndIf=154, DirectiveLine=155, Error=156, Warning=157, Region=158, EndRegion=159, 
		Pragma=160, Nullable=161, Include=162, IncludeAgain=163, DllLoad=164, 
		Requires=165, SingleInstance=166, Persistent=167, Warn=168, HookMutexName=169, 
		NoDynamicVars=170, ErrorStdOut=171, ClipboardTimeout=172, HotIfTimeout=173, 
		MaxThreads=174, MaxThreadsBuffer=175, MaxThreadsPerHotkey=176, WinActivateForce=177, 
		NoMainWindow=178, NoTrayIcon=179, Assembly=180, DirectiveHidden=181, ConditionalSymbol=182, 
		DirectiveSingleLineComment=183, DirectiveNewline=184, UnexpectedDirectiveCharacter=185, 
		ImportDirectiveSingleLineComment=186, ImportDirectiveLineContinuation=187, 
		UnexpectedImportDirectiveCharacter=188, DirectiveTextWhitespace=189, UnexpectedTextDirectiveCharacter=190, 
		HotstringNewline=191, NoMouse=192, EndChars=193, HotstringOptions=194;
	public const int
		RULE_preprocessor_directive = 0, RULE_directive_new_line_or_sharp = 1, 
		RULE_importDirective = 2, RULE_importModule = 3, RULE_importList = 4, 
		RULE_importSpecifierList = 5, RULE_importSpecifier = 6, RULE_importModuleName = 7, 
		RULE_importDirectiveIdentifier = 8, RULE_preprocessor_expression = 9;
	public static readonly string[] ruleNames = {
		"preprocessor_directive", "directive_new_line_or_sharp", "importDirective", 
		"importModule", "importList", "importSpecifierList", "importSpecifier", 
		"importModuleName", "importDirectiveIdentifier", "preprocessor_expression"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"'['", "']'", "'('", "')'", "'{'", "'}'", "','", "':='", "'?'", "'?.'", 
		"':'", "'::'", "'...'", "'.'", "'++'", "'--'", "'+'", "'-'", "'~'", "'!'", 
		"'*'", "'/'", "'//'", "'%'", "'**'", "'??'", "'#'", "'>>'", "'<<'", "'>>>'", 
		"'<'", "'>'", "'<='", "'>='", "'='", "'!='", "'=='", "'!=='", "'~='", 
		"'&'", "'^'", "'|'", "'&&'", "'||'", "'*='", "'/='", "'%='", "'+='", "'-='", 
		"'<<='", "'>>='", "'>>>='", "'//='", "'.='", "'&='", "'^='", "'|='", "'**='", 
		"'??='", "'=>'", "'null'", "'unset'", "'true'", "'false'", null, null, 
		null, null, null, null, null, null, null, "'break'", "'do'", "'instanceof'", 
		"'switch'", "'case'", "'default'", "'else'", "'catch'", "'finally'", "'return'", 
		"'continue'", "'for'", "'while'", "'parse'", "'reg'", "'read'", "'files'", 
		"'loop'", "'until'", "'this'", "'if'", "'throw'", "'delete'", "'in'", 
		"'try'", "'yield'", "'is'", "'contains'", "'and'", "'not'", "'or'", "'goto'", 
		"'get'", "'set'", "'class'", "'enum'", "'extends'", "'super'", "'base'", 
		"'export'", "'import'", "'from'", "'as'", "'async'", "'await'", "'static'", 
		"'global'", "'local'", null, null, null, null, null, null, null, null, 
		null, null, null, null, "'hotif'", "'inputlevel'", "'suspendexempt'", 
		"'usehook'", null, null, "'define'", "'undef'", "'elif'", "'endif'", "'line'", 
		null, null, null, null, null, null, null, null, null, null, null, "'persistent'", 
		null, null, "'nodynamicvars'", "'errorstdout'", "'clipboardtimeout'", 
		"'hotiftimeout'", "'maxthreads'", "'maxthreadsbuffer'", "'maxthreadsperhotkey'", 
		"'winactivateforce'", "'nomainwindow'", "'notrayicon'", null, "'hidden'", 
		null, null, null, null, null, null, null, null, null, null, "'NoMouse'", 
		"'EndChars'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "DerefStart", "DerefEnd", "ObjectLiteralStart", "ObjectLiteralEnd", 
		"ConcatDot", "Maybe", "SingleLineBlockComment", "SingleLineComment", "HotstringTrigger", 
		"RemapKey", "HotkeyTrigger", "OpenBracket", "CloseBracket", "OpenParen", 
		"CloseParen", "OpenBrace", "CloseBrace", "Comma", "Assign", "QuestionMark", 
		"QuestionMarkDot", "Colon", "DoubleColon", "Ellipsis", "Dot", "PlusPlus", 
		"MinusMinus", "Plus", "Minus", "BitNot", "Not", "Multiply", "Divide", 
		"IntegerDivide", "Modulus", "Power", "NullCoalesce", "Hashtag", "RightShiftArithmetic", 
		"LeftShiftArithmetic", "RightShiftLogical", "LessThan", "MoreThan", "LessThanEquals", 
		"GreaterThanEquals", "Equals_", "NotEquals", "IdentityEquals", "IdentityNotEquals", 
		"RegExMatch", "BitAnd", "BitXOr", "BitOr", "And", "Or", "MultiplyAssign", 
		"DivideAssign", "ModulusAssign", "PlusAssign", "MinusAssign", "LeftShiftArithmeticAssign", 
		"RightShiftArithmeticAssign", "RightShiftLogicalAssign", "IntegerDivideAssign", 
		"ConcatenateAssign", "BitAndAssign", "BitXorAssign", "BitOrAssign", "PowerAssign", 
		"NullishCoalescingAssign", "Arrow", "NullLiteral", "Unset", "True", "False", 
		"DecimalLiteral", "HexIntegerLiteral", "OctalIntegerLiteral", "OctalIntegerLiteral2", 
		"BinaryIntegerLiteral", "BigHexIntegerLiteral", "BigOctalIntegerLiteral", 
		"BigBinaryIntegerLiteral", "BigDecimalIntegerLiteral", "Break", "Do", 
		"Instanceof", "Switch", "Case", "Default", "Else", "Catch", "Finally", 
		"Return", "Continue", "For", "While", "Parse", "Reg", "Read", "Files", 
		"Loop", "Until", "This", "If", "Throw", "Delete", "In", "Try", "Yield", 
		"Is", "Contains", "VerbalAnd", "VerbalNot", "VerbalOr", "Goto", "Get", 
		"Set", "Class", "Enum", "Extends", "Super", "Base", "Export", "Import", 
		"From", "As", "Async", "Await", "Static", "Global", "Local", "Identifier", 
		"ContinuationSection", "StringLiteral", "EOL", "WS", "UnexpectedCharacter", 
		"StringLiteralPart", "StringModeTerminator", "StringModeTrivia", "StringModeContinuationSection", 
		"HotstringExpansion", "Digits", "HotIf", "InputLevel", "SuspendExempt", 
		"UseHook", "Hotstring", "Module", "Define", "Undef", "ElIf", "EndIf", 
		"DirectiveLine", "Error", "Warning", "Region", "EndRegion", "Pragma", 
		"Nullable", "Include", "IncludeAgain", "DllLoad", "Requires", "SingleInstance", 
		"Persistent", "Warn", "HookMutexName", "NoDynamicVars", "ErrorStdOut", 
		"ClipboardTimeout", "HotIfTimeout", "MaxThreads", "MaxThreadsBuffer", 
		"MaxThreadsPerHotkey", "WinActivateForce", "NoMainWindow", "NoTrayIcon", 
		"Assembly", "DirectiveHidden", "ConditionalSymbol", "DirectiveSingleLineComment", 
		"DirectiveNewline", "UnexpectedDirectiveCharacter", "ImportDirectiveSingleLineComment", 
		"ImportDirectiveLineContinuation", "UnexpectedImportDirectiveCharacter", 
		"DirectiveTextWhitespace", "UnexpectedTextDirectiveCharacter", "HotstringNewline", 
		"NoMouse", "EndChars", "HotstringOptions"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PreprocessorParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PreprocessorParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PreprocessorParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PreprocessorParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Preprocessor_directiveContext : ParserRuleContext {
		public Boolean value;
		public Preprocessor_directiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_directive; } }
	 
		public Preprocessor_directiveContext() { }
		public virtual void CopyFrom(Preprocessor_directiveContext context) {
			base.CopyFrom(context);
			this.value = context.value;
		}
	}
	public partial class PreprocessorNoTrayIconContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NoTrayIcon() { return GetToken(PreprocessorParser.NoTrayIcon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNoTrayIconContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNoTrayIcon(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNullableContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Nullable() { return GetToken(PreprocessorParser.Nullable, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNullableContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNullable(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorDeclarationContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Define() { return GetToken(PreprocessorParser.Define, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ConditionalSymbol() { return GetToken(PreprocessorParser.ConditionalSymbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Undef() { return GetToken(PreprocessorParser.Undef, 0); }
		public PreprocessorDeclarationContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorPragmaContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pragma() { return GetToken(PreprocessorParser.Pragma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorPragmaContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorPragma(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNoDynamicVarsContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NoDynamicVars() { return GetToken(PreprocessorParser.NoDynamicVars, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNoDynamicVarsContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNoDynamicVars(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorWinActivateForceContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WinActivateForce() { return GetToken(PreprocessorParser.WinActivateForce, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorWinActivateForceContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorWinActivateForce(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorLineContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DirectiveLine() { return GetToken(PreprocessorParser.DirectiveLine, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Default() { return GetToken(PreprocessorParser.Default, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DirectiveHidden() { return GetToken(PreprocessorParser.DirectiveHidden, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		public PreprocessorLineContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorLine(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNoMainWindowContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NoMainWindow() { return GetToken(PreprocessorParser.NoMainWindow, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNoMainWindowContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNoMainWindow(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorTextualDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Include() { return GetToken(PreprocessorParser.Include, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IncludeAgain() { return GetToken(PreprocessorParser.IncludeAgain, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DllLoad() { return GetToken(PreprocessorParser.DllLoad, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Requires() { return GetToken(PreprocessorParser.Requires, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assembly() { return GetToken(PreprocessorParser.Assembly, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HookMutexName() { return GetToken(PreprocessorParser.HookMutexName, 0); }
		public PreprocessorTextualDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorTextualDirective(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorPersistentContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Persistent() { return GetToken(PreprocessorParser.Persistent, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode True() { return GetToken(PreprocessorParser.True, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode False() { return GetToken(PreprocessorParser.False, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		public PreprocessorPersistentContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorPersistent(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorDiagnosticContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Error() { return GetToken(PreprocessorParser.Error, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Warning() { return GetToken(PreprocessorParser.Warning, 0); }
		public PreprocessorDiagnosticContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorDiagnostic(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorErrorStdOutContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ErrorStdOut() { return GetToken(PreprocessorParser.ErrorStdOut, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorErrorStdOutContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorErrorStdOut(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorRegionContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Region() { return GetToken(PreprocessorParser.Region, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndRegion() { return GetToken(PreprocessorParser.EndRegion, 0); }
		public PreprocessorRegionContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorRegion(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorOptionalTextualDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Module() { return GetToken(PreprocessorParser.Module, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Warn() { return GetToken(PreprocessorParser.Warn, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SingleInstance() { return GetToken(PreprocessorParser.SingleInstance, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		public PreprocessorOptionalTextualDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorOptionalTextualDirective(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorConditionalContext : Preprocessor_directiveContext {
		public Preprocessor_expressionContext expr;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode If() { return GetToken(PreprocessorParser.If, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_expressionContext preprocessor_expression() {
			return GetRuleContext<Preprocessor_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ElIf() { return GetToken(PreprocessorParser.ElIf, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Else() { return GetToken(PreprocessorParser.Else, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndIf() { return GetToken(PreprocessorParser.EndIf, 0); }
		public PreprocessorConditionalContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorConditional(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorImportDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Import() { return GetToken(PreprocessorParser.Import, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ImportDirectiveContext importDirective() {
			return GetRuleContext<ImportDirectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorImportDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorImportDirective(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNumericDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HotIfTimeout() { return GetToken(PreprocessorParser.HotIfTimeout, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MaxThreads() { return GetToken(PreprocessorParser.MaxThreads, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MaxThreadsBuffer() { return GetToken(PreprocessorParser.MaxThreadsBuffer, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MaxThreadsPerHotkey() { return GetToken(PreprocessorParser.MaxThreadsPerHotkey, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ClipboardTimeout() { return GetToken(PreprocessorParser.ClipboardTimeout, 0); }
		public PreprocessorNumericDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNumericDirective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_directiveContext preprocessor_directive() {
		Preprocessor_directiveContext _localctx = new Preprocessor_directiveContext(Context, State);
		EnterRule(_localctx, 0, RULE_preprocessor_directive);
		int _la;
		try {
			State = 124;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Define:
				_localctx = new PreprocessorDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 20;
				Match(Define);
				State = 21;
				Match(ConditionalSymbol);
				State = 22;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveDefine(); 
				}
				break;
			case Undef:
				_localctx = new PreprocessorDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 25;
				Match(Undef);
				State = 26;
				Match(ConditionalSymbol);
				State = 27;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveUndef(); 
				}
				break;
			case If:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 30;
				Match(If);
				State = 31;
				((PreprocessorConditionalContext)_localctx).expr = preprocessor_expression(0);
				State = 32;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveIf(); 
				}
				break;
			case ElIf:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 35;
				Match(ElIf);
				State = 36;
				((PreprocessorConditionalContext)_localctx).expr = preprocessor_expression(0);
				State = 37;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveElif(); 
				}
				break;
			case Else:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 40;
				Match(Else);
				State = 41;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveElse(); 
				}
				break;
			case EndIf:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 44;
				Match(EndIf);
				State = 45;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveEndif(); 
				}
				break;
			case DirectiveLine:
				_localctx = new PreprocessorLineContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 48;
				Match(DirectiveLine);
				State = 55;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Digits:
					{
					State = 49;
					Match(Digits);
					State = 51;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==StringLiteral) {
						{
						State = 50;
						Match(StringLiteral);
						}
					}

					}
					break;
				case Default:
					{
					State = 53;
					Match(Default);
					}
					break;
				case DirectiveHidden:
					{
					State = 54;
					Match(DirectiveHidden);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 57;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveLine(); 
				}
				break;
			case Error:
				_localctx = new PreprocessorDiagnosticContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 60;
				Match(Error);
				State = 61;
				Match(StringLiteral);
				State = 62;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveError(); 
				}
				break;
			case Warning:
				_localctx = new PreprocessorDiagnosticContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 65;
				Match(Warning);
				State = 66;
				Match(StringLiteral);
				State = 67;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveWarning(); 
				}
				break;
			case Region:
				_localctx = new PreprocessorRegionContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 70;
				Match(Region);
				State = 72;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==StringLiteral) {
					{
					State = 71;
					Match(StringLiteral);
					}
				}

				State = 74;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveRegion(); 
				}
				break;
			case EndRegion:
				_localctx = new PreprocessorRegionContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 77;
				Match(EndRegion);
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==StringLiteral) {
					{
					State = 78;
					Match(StringLiteral);
					}
				}

				State = 81;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveEndregion(); 
				}
				break;
			case Pragma:
				_localctx = new PreprocessorPragmaContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 84;
				Match(Pragma);
				State = 85;
				Match(StringLiteral);
				State = 86;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectivePragma(); 
				}
				break;
			case Nullable:
				_localctx = new PreprocessorNullableContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 89;
				Match(Nullable);
				State = 90;
				Match(StringLiteral);
				State = 91;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveNullable(); 
				}
				break;
			case Import:
				_localctx = new PreprocessorImportDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 14);
				{
				State = 94;
				Match(Import);
				State = 95;
				importDirective();
				State = 96;
				directive_new_line_or_sharp();
				}
				break;
			case Include:
			case IncludeAgain:
			case DllLoad:
			case Requires:
			case HookMutexName:
			case Assembly:
				_localctx = new PreprocessorTextualDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 15);
				{
				State = 98;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 162)) & ~0x3f) == 0 && ((1L << (_la - 162)) & 262287L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 99;
				Match(StringLiteral);
				State = 100;
				directive_new_line_or_sharp();
				}
				break;
			case Persistent:
				_localctx = new PreprocessorPersistentContext(_localctx);
				EnterOuterAlt(_localctx, 16);
				{
				State = 101;
				Match(Persistent);
				State = 103;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==True || _la==False || _la==Digits) {
					{
					State = 102;
					_la = TokenStream.LA(1);
					if ( !(_la==True || _la==False || _la==Digits) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 105;
				directive_new_line_or_sharp();
				}
				break;
			case Module:
			case SingleInstance:
			case Warn:
				_localctx = new PreprocessorOptionalTextualDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 17);
				{
				State = 106;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 150)) & ~0x3f) == 0 && ((1L << (_la - 150)) & 327681L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==StringLiteral) {
					{
					State = 107;
					Match(StringLiteral);
					}
				}

				State = 110;
				directive_new_line_or_sharp();
				}
				break;
			case NoDynamicVars:
				_localctx = new PreprocessorNoDynamicVarsContext(_localctx);
				EnterOuterAlt(_localctx, 18);
				{
				State = 111;
				Match(NoDynamicVars);
				State = 112;
				directive_new_line_or_sharp();
				}
				break;
			case ErrorStdOut:
				_localctx = new PreprocessorErrorStdOutContext(_localctx);
				EnterOuterAlt(_localctx, 19);
				{
				State = 113;
				Match(ErrorStdOut);
				State = 114;
				directive_new_line_or_sharp();
				}
				break;
			case WinActivateForce:
				_localctx = new PreprocessorWinActivateForceContext(_localctx);
				EnterOuterAlt(_localctx, 20);
				{
				State = 115;
				Match(WinActivateForce);
				State = 116;
				directive_new_line_or_sharp();
				}
				break;
			case NoTrayIcon:
				_localctx = new PreprocessorNoTrayIconContext(_localctx);
				EnterOuterAlt(_localctx, 21);
				{
				State = 117;
				Match(NoTrayIcon);
				State = 118;
				directive_new_line_or_sharp();
				}
				break;
			case NoMainWindow:
				_localctx = new PreprocessorNoMainWindowContext(_localctx);
				EnterOuterAlt(_localctx, 22);
				{
				State = 119;
				Match(NoMainWindow);
				State = 120;
				directive_new_line_or_sharp();
				}
				break;
			case ClipboardTimeout:
			case HotIfTimeout:
			case MaxThreads:
			case MaxThreadsBuffer:
			case MaxThreadsPerHotkey:
				_localctx = new PreprocessorNumericDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 23);
				{
				State = 121;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 172)) & ~0x3f) == 0 && ((1L << (_la - 172)) & 31L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 122;
				Match(Digits);
				State = 123;
				directive_new_line_or_sharp();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Directive_new_line_or_sharpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DirectiveNewline() { return GetToken(PreprocessorParser.DirectiveNewline, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PreprocessorParser.Eof, 0); }
		public Directive_new_line_or_sharpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directive_new_line_or_sharp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDirective_new_line_or_sharp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
		Directive_new_line_or_sharpContext _localctx = new Directive_new_line_or_sharpContext(Context, State);
		EnterRule(_localctx, 2, RULE_directive_new_line_or_sharp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==DirectiveNewline) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportDirectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ImportModuleContext importModule() {
			return GetRuleContext<ImportModuleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Export() { return GetToken(PreprocessorParser.Export, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ImportListContext importList() {
			return GetRuleContext<ImportListContext>(0);
		}
		public ImportDirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importDirective; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportDirective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportDirectiveContext importDirective() {
		ImportDirectiveContext _localctx = new ImportDirectiveContext(Context, State);
		EnterRule(_localctx, 4, RULE_importDirective);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Export) {
				{
				State = 128;
				Match(Export);
				}
			}

			State = 131;
			importModule();
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==OpenBrace) {
				{
				State = 132;
				importList();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportModuleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ImportModuleNameContext importModuleName() {
			return GetRuleContext<ImportModuleNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode As() { return GetToken(PreprocessorParser.As, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ImportDirectiveIdentifierContext importDirectiveIdentifier() {
			return GetRuleContext<ImportDirectiveIdentifierContext>(0);
		}
		public ImportModuleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importModule; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportModule(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportModuleContext importModule() {
		ImportModuleContext _localctx = new ImportModuleContext(Context, State);
		EnterRule(_localctx, 6, RULE_importModule);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			importModuleName();
			State = 138;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==As) {
				{
				State = 136;
				Match(As);
				State = 137;
				importDirectiveIdentifier();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenBrace() { return GetToken(PreprocessorParser.OpenBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseBrace() { return GetToken(PreprocessorParser.CloseBrace, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ImportSpecifierListContext importSpecifierList() {
			return GetRuleContext<ImportSpecifierListContext>(0);
		}
		public ImportListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportListContext importList() {
		ImportListContext _localctx = new ImportListContext(Context, State);
		EnterRule(_localctx, 8, RULE_importList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140;
			Match(OpenBrace);
			State = 142;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Multiply || _la==Identifier) {
				{
				State = 141;
				importSpecifierList();
				}
			}

			State = 144;
			Match(CloseBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportSpecifierListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ImportSpecifierContext[] importSpecifier() {
			return GetRuleContexts<ImportSpecifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ImportSpecifierContext importSpecifier(int i) {
			return GetRuleContext<ImportSpecifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(PreprocessorParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(PreprocessorParser.Comma, i);
		}
		public ImportSpecifierListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importSpecifierList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportSpecifierList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportSpecifierListContext importSpecifierList() {
		ImportSpecifierListContext _localctx = new ImportSpecifierListContext(Context, State);
		EnterRule(_localctx, 10, RULE_importSpecifierList);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			importSpecifier();
			State = 151;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 147;
					Match(Comma);
					State = 148;
					importSpecifier();
					}
					} 
				}
				State = 153;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			}
			State = 155;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Comma) {
				{
				State = 154;
				Match(Comma);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportSpecifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Multiply() { return GetToken(PreprocessorParser.Multiply, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ImportDirectiveIdentifierContext[] importDirectiveIdentifier() {
			return GetRuleContexts<ImportDirectiveIdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ImportDirectiveIdentifierContext importDirectiveIdentifier(int i) {
			return GetRuleContext<ImportDirectiveIdentifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode As() { return GetToken(PreprocessorParser.As, 0); }
		public ImportSpecifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importSpecifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportSpecifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportSpecifierContext importSpecifier() {
		ImportSpecifierContext _localctx = new ImportSpecifierContext(Context, State);
		EnterRule(_localctx, 12, RULE_importSpecifier);
		int _la;
		try {
			State = 163;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Multiply:
				EnterOuterAlt(_localctx, 1);
				{
				State = 157;
				Match(Multiply);
				}
				break;
			case Identifier:
				EnterOuterAlt(_localctx, 2);
				{
				State = 158;
				importDirectiveIdentifier();
				State = 161;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==As) {
					{
					State = 159;
					Match(As);
					State = 160;
					importDirectiveIdentifier();
					}
				}

				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportModuleNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ImportDirectiveIdentifierContext importDirectiveIdentifier() {
			return GetRuleContext<ImportDirectiveIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		public ImportModuleNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importModuleName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportModuleName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportModuleNameContext importModuleName() {
		ImportModuleNameContext _localctx = new ImportModuleNameContext(Context, State);
		EnterRule(_localctx, 14, RULE_importModuleName);
		try {
			State = 167;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Identifier:
				EnterOuterAlt(_localctx, 1);
				{
				State = 165;
				importDirectiveIdentifier();
				}
				break;
			case StringLiteral:
				EnterOuterAlt(_localctx, 2);
				{
				State = 166;
				Match(StringLiteral);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImportDirectiveIdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(PreprocessorParser.Identifier, 0); }
		public ImportDirectiveIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_importDirectiveIdentifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportDirectiveIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ImportDirectiveIdentifierContext importDirectiveIdentifier() {
		ImportDirectiveIdentifierContext _localctx = new ImportDirectiveIdentifierContext(Context, State);
		EnterRule(_localctx, 16, RULE_importDirectiveIdentifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_expressionContext : ParserRuleContext {
		public String value;
		public Preprocessor_expressionContext expr1;
		public Preprocessor_expressionContext expr;
		public Preprocessor_expressionContext expr2;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode True() { return GetToken(PreprocessorParser.True, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode False() { return GetToken(PreprocessorParser.False, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ConditionalSymbol() { return GetToken(PreprocessorParser.ConditionalSymbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(PreprocessorParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(PreprocessorParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_expressionContext[] preprocessor_expression() {
			return GetRuleContexts<Preprocessor_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_expressionContext preprocessor_expression(int i) {
			return GetRuleContext<Preprocessor_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Not() { return GetToken(PreprocessorParser.Not, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IdentityEquals() { return GetToken(PreprocessorParser.IdentityEquals, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NotEquals() { return GetToken(PreprocessorParser.NotEquals, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(PreprocessorParser.And, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Or() { return GetToken(PreprocessorParser.Or, 0); }
		public Preprocessor_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessor_expression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_expressionContext preprocessor_expression() {
		return preprocessor_expression(0);
	}

	private Preprocessor_expressionContext preprocessor_expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Preprocessor_expressionContext _localctx = new Preprocessor_expressionContext(Context, _parentState);
		Preprocessor_expressionContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_preprocessor_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case True:
				{
				State = 172;
				Match(True);
				 this.OnPreprocessorExpressionTrue(); 
				}
				break;
			case False:
				{
				State = 174;
				Match(False);
				 this.OnPreprocessorExpressionFalse(); 
				}
				break;
			case Digits:
				{
				State = 176;
				Match(Digits);
				 this.OnPreprocessorExpressionDigits(); 
				}
				break;
			case ConditionalSymbol:
				{
				State = 178;
				Match(ConditionalSymbol);
				 this.OnPreprocessorExpressionConditionalSymbol(); 
				}
				break;
			case OpenParen:
				{
				State = 180;
				Match(OpenParen);
				State = 181;
				_localctx.expr = preprocessor_expression(0);
				State = 182;
				Match(CloseParen);
				 this.OnPreprocessorExpressionConditionalOpenParens(); 
				}
				break;
			case Not:
				{
				State = 185;
				Match(Not);
				State = 186;
				_localctx.expr = preprocessor_expression(5);
				 this.OnPreprocessorExpressionConditionalNot(); 
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 213;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 211;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
					case 1:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 191;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 192;
						Match(IdentityEquals);
						State = 193;
						_localctx.expr2 = preprocessor_expression(5);
						 this.OnPreprocessorExpressionConditionalEq(); 
						}
						break;
					case 2:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 196;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 197;
						Match(NotEquals);
						State = 198;
						_localctx.expr2 = preprocessor_expression(4);
						 this.OnPreprocessorExpressionConditionalNe(); 
						}
						break;
					case 3:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 201;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 202;
						Match(And);
						State = 203;
						_localctx.expr2 = preprocessor_expression(3);
						 this.OnPreprocessorExpressionConditionalAnd(); 
						}
						break;
					case 4:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 206;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 207;
						Match(Or);
						State = 208;
						_localctx.expr2 = preprocessor_expression(2);
						 this.OnPreprocessorExpressionConditionalOr(); 
						}
						break;
					}
					} 
				}
				State = 215;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 9: return preprocessor_expression_sempred((Preprocessor_expressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool preprocessor_expression_sempred(Preprocessor_expressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,194,217,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,
		7,7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
		0,1,0,3,0,52,8,0,1,0,1,0,3,0,56,8,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
		0,1,0,1,0,1,0,1,0,1,0,1,0,3,0,73,8,0,1,0,1,0,1,0,1,0,1,0,3,0,80,8,0,1,
		0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,3,0,104,8,0,1,0,1,0,1,0,3,0,109,8,0,1,0,1,0,1,0,1,0,1,
		0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,3,0,125,8,0,1,1,1,1,1,2,3,2,130,
		8,2,1,2,1,2,3,2,134,8,2,1,3,1,3,1,3,3,3,139,8,3,1,4,1,4,3,4,143,8,4,1,
		4,1,4,1,5,1,5,1,5,5,5,150,8,5,10,5,12,5,153,9,5,1,5,3,5,156,8,5,1,6,1,
		6,1,6,1,6,3,6,162,8,6,3,6,164,8,6,1,7,1,7,3,7,168,8,7,1,8,1,8,1,9,1,9,
		1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,3,9,190,
		8,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,
		9,1,9,1,9,1,9,5,9,212,8,9,10,9,12,9,215,9,9,1,9,0,1,18,10,0,2,4,6,8,10,
		12,14,16,18,0,5,3,0,162,165,169,169,180,180,2,0,74,75,144,144,3,0,150,
		150,166,166,168,168,1,0,172,176,1,1,184,184,253,0,124,1,0,0,0,2,126,1,
		0,0,0,4,129,1,0,0,0,6,135,1,0,0,0,8,140,1,0,0,0,10,146,1,0,0,0,12,163,
		1,0,0,0,14,167,1,0,0,0,16,169,1,0,0,0,18,189,1,0,0,0,20,21,5,151,0,0,21,
		22,5,182,0,0,22,23,3,2,1,0,23,24,6,0,-1,0,24,125,1,0,0,0,25,26,5,152,0,
		0,26,27,5,182,0,0,27,28,3,2,1,0,28,29,6,0,-1,0,29,125,1,0,0,0,30,31,5,
		105,0,0,31,32,3,18,9,0,32,33,3,2,1,0,33,34,6,0,-1,0,34,125,1,0,0,0,35,
		36,5,153,0,0,36,37,3,18,9,0,37,38,3,2,1,0,38,39,6,0,-1,0,39,125,1,0,0,
		0,40,41,5,91,0,0,41,42,3,2,1,0,42,43,6,0,-1,0,43,125,1,0,0,0,44,45,5,154,
		0,0,45,46,3,2,1,0,46,47,6,0,-1,0,47,125,1,0,0,0,48,55,5,155,0,0,49,51,
		5,144,0,0,50,52,5,135,0,0,51,50,1,0,0,0,51,52,1,0,0,0,52,56,1,0,0,0,53,
		56,5,90,0,0,54,56,5,181,0,0,55,49,1,0,0,0,55,53,1,0,0,0,55,54,1,0,0,0,
		56,57,1,0,0,0,57,58,3,2,1,0,58,59,6,0,-1,0,59,125,1,0,0,0,60,61,5,156,
		0,0,61,62,5,135,0,0,62,63,3,2,1,0,63,64,6,0,-1,0,64,125,1,0,0,0,65,66,
		5,157,0,0,66,67,5,135,0,0,67,68,3,2,1,0,68,69,6,0,-1,0,69,125,1,0,0,0,
		70,72,5,158,0,0,71,73,5,135,0,0,72,71,1,0,0,0,72,73,1,0,0,0,73,74,1,0,
		0,0,74,75,3,2,1,0,75,76,6,0,-1,0,76,125,1,0,0,0,77,79,5,159,0,0,78,80,
		5,135,0,0,79,78,1,0,0,0,79,80,1,0,0,0,80,81,1,0,0,0,81,82,3,2,1,0,82,83,
		6,0,-1,0,83,125,1,0,0,0,84,85,5,160,0,0,85,86,5,135,0,0,86,87,3,2,1,0,
		87,88,6,0,-1,0,88,125,1,0,0,0,89,90,5,161,0,0,90,91,5,135,0,0,91,92,3,
		2,1,0,92,93,6,0,-1,0,93,125,1,0,0,0,94,95,5,125,0,0,95,96,3,4,2,0,96,97,
		3,2,1,0,97,125,1,0,0,0,98,99,7,0,0,0,99,100,5,135,0,0,100,125,3,2,1,0,
		101,103,5,167,0,0,102,104,7,1,0,0,103,102,1,0,0,0,103,104,1,0,0,0,104,
		105,1,0,0,0,105,125,3,2,1,0,106,108,7,2,0,0,107,109,5,135,0,0,108,107,
		1,0,0,0,108,109,1,0,0,0,109,110,1,0,0,0,110,125,3,2,1,0,111,112,5,170,
		0,0,112,125,3,2,1,0,113,114,5,171,0,0,114,125,3,2,1,0,115,116,5,177,0,
		0,116,125,3,2,1,0,117,118,5,179,0,0,118,125,3,2,1,0,119,120,5,178,0,0,
		120,125,3,2,1,0,121,122,7,3,0,0,122,123,5,144,0,0,123,125,3,2,1,0,124,
		20,1,0,0,0,124,25,1,0,0,0,124,30,1,0,0,0,124,35,1,0,0,0,124,40,1,0,0,0,
		124,44,1,0,0,0,124,48,1,0,0,0,124,60,1,0,0,0,124,65,1,0,0,0,124,70,1,0,
		0,0,124,77,1,0,0,0,124,84,1,0,0,0,124,89,1,0,0,0,124,94,1,0,0,0,124,98,
		1,0,0,0,124,101,1,0,0,0,124,106,1,0,0,0,124,111,1,0,0,0,124,113,1,0,0,
		0,124,115,1,0,0,0,124,117,1,0,0,0,124,119,1,0,0,0,124,121,1,0,0,0,125,
		1,1,0,0,0,126,127,7,4,0,0,127,3,1,0,0,0,128,130,5,124,0,0,129,128,1,0,
		0,0,129,130,1,0,0,0,130,131,1,0,0,0,131,133,3,6,3,0,132,134,3,8,4,0,133,
		132,1,0,0,0,133,134,1,0,0,0,134,5,1,0,0,0,135,138,3,14,7,0,136,137,5,127,
		0,0,137,139,3,16,8,0,138,136,1,0,0,0,138,139,1,0,0,0,139,7,1,0,0,0,140,
		142,5,16,0,0,141,143,3,10,5,0,142,141,1,0,0,0,142,143,1,0,0,0,143,144,
		1,0,0,0,144,145,5,17,0,0,145,9,1,0,0,0,146,151,3,12,6,0,147,148,5,18,0,
		0,148,150,3,12,6,0,149,147,1,0,0,0,150,153,1,0,0,0,151,149,1,0,0,0,151,
		152,1,0,0,0,152,155,1,0,0,0,153,151,1,0,0,0,154,156,5,18,0,0,155,154,1,
		0,0,0,155,156,1,0,0,0,156,11,1,0,0,0,157,164,5,32,0,0,158,161,3,16,8,0,
		159,160,5,127,0,0,160,162,3,16,8,0,161,159,1,0,0,0,161,162,1,0,0,0,162,
		164,1,0,0,0,163,157,1,0,0,0,163,158,1,0,0,0,164,13,1,0,0,0,165,168,3,16,
		8,0,166,168,5,135,0,0,167,165,1,0,0,0,167,166,1,0,0,0,168,15,1,0,0,0,169,
		170,5,133,0,0,170,17,1,0,0,0,171,172,6,9,-1,0,172,173,5,74,0,0,173,190,
		6,9,-1,0,174,175,5,75,0,0,175,190,6,9,-1,0,176,177,5,144,0,0,177,190,6,
		9,-1,0,178,179,5,182,0,0,179,190,6,9,-1,0,180,181,5,14,0,0,181,182,3,18,
		9,0,182,183,5,15,0,0,183,184,6,9,-1,0,184,190,1,0,0,0,185,186,5,31,0,0,
		186,187,3,18,9,5,187,188,6,9,-1,0,188,190,1,0,0,0,189,171,1,0,0,0,189,
		174,1,0,0,0,189,176,1,0,0,0,189,178,1,0,0,0,189,180,1,0,0,0,189,185,1,
		0,0,0,190,213,1,0,0,0,191,192,10,4,0,0,192,193,5,48,0,0,193,194,3,18,9,
		5,194,195,6,9,-1,0,195,212,1,0,0,0,196,197,10,3,0,0,197,198,5,47,0,0,198,
		199,3,18,9,4,199,200,6,9,-1,0,200,212,1,0,0,0,201,202,10,2,0,0,202,203,
		5,54,0,0,203,204,3,18,9,3,204,205,6,9,-1,0,205,212,1,0,0,0,206,207,10,
		1,0,0,207,208,5,55,0,0,208,209,3,18,9,2,209,210,6,9,-1,0,210,212,1,0,0,
		0,211,191,1,0,0,0,211,196,1,0,0,0,211,201,1,0,0,0,211,206,1,0,0,0,212,
		215,1,0,0,0,213,211,1,0,0,0,213,214,1,0,0,0,214,19,1,0,0,0,215,213,1,0,
		0,0,19,51,55,72,79,103,108,124,129,133,138,142,151,155,161,163,167,189,
		211,213
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Keysharp.Parsing.Antlr
