//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/minip/source/repos/Keysharp_clone/Keysharp.Core/Scripting/Parser/Antlr/PreprocessorParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class PreprocessorParser : PreprocessorParserBase {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		DerefStart=1, DerefEnd=2, ObjectLiteralStart=3, ObjectLiteralEnd=4, ConcatDot=5, 
		Maybe=6, SingleLineBlockComment=7, SingleLineComment=8, HotstringTrigger=9, 
		RemapKey=10, HotkeyTrigger=11, OpenBracket=12, CloseBracket=13, OpenParen=14, 
		CloseParen=15, OpenBrace=16, CloseBrace=17, Comma=18, Assign=19, QuestionMark=20, 
		QuestionMarkDot=21, Colon=22, DoubleColon=23, Ellipsis=24, Dot=25, PlusPlus=26, 
		MinusMinus=27, Plus=28, Minus=29, BitNot=30, Not=31, Multiply=32, Divide=33, 
		IntegerDivide=34, Modulus=35, Power=36, NullCoalesce=37, Hashtag=38, RightShiftArithmetic=39, 
		LeftShiftArithmetic=40, RightShiftLogical=41, LessThan=42, MoreThan=43, 
		LessThanEquals=44, GreaterThanEquals=45, Equals_=46, NotEquals=47, IdentityEquals=48, 
		IdentityNotEquals=49, RegExMatch=50, BitAnd=51, BitXOr=52, BitOr=53, And=54, 
		Or=55, MultiplyAssign=56, DivideAssign=57, ModulusAssign=58, PlusAssign=59, 
		MinusAssign=60, LeftShiftArithmeticAssign=61, RightShiftArithmeticAssign=62, 
		RightShiftLogicalAssign=63, IntegerDivideAssign=64, ConcatenateAssign=65, 
		BitAndAssign=66, BitXorAssign=67, BitOrAssign=68, PowerAssign=69, NullishCoalescingAssign=70, 
		Arrow=71, NullLiteral=72, Unset=73, True=74, False=75, DecimalLiteral=76, 
		HexIntegerLiteral=77, OctalIntegerLiteral=78, OctalIntegerLiteral2=79, 
		BinaryIntegerLiteral=80, BigHexIntegerLiteral=81, BigOctalIntegerLiteral=82, 
		BigBinaryIntegerLiteral=83, BigDecimalIntegerLiteral=84, Break=85, Do=86, 
		Instanceof=87, Switch=88, Case=89, Default=90, Else=91, Catch=92, Finally=93, 
		Return=94, Continue=95, For=96, While=97, Parse=98, Reg=99, Read=100, 
		Files=101, Loop=102, Until=103, This=104, If=105, Throw=106, Delete=107, 
		In=108, Try=109, Yield=110, Is=111, Contains=112, VerbalAnd=113, VerbalNot=114, 
		VerbalOr=115, Goto=116, Get=117, Set=118, Class=119, Enum=120, Extends=121, 
		Super=122, Base=123, Export=124, Import=125, From=126, As=127, Async=128, 
		Await=129, Static=130, Global=131, Local=132, Identifier=133, ContinuationSection=134, 
		StringLiteral=135, EOL=136, WS=137, UnexpectedCharacter=138, StringLiteralPart=139, 
		StringModeTerminator=140, StringModeTrivia=141, StringModeContinuationSection=142, 
		HotstringExpansion=143, Digits=144, HotIf=145, InputLevel=146, SuspendExempt=147, 
		UseHook=148, Hotstring=149, Module=150, Define=151, Undef=152, ElIf=153, 
		EndIf=154, DirectiveLine=155, Error=156, Warning=157, Region=158, EndRegion=159, 
		Pragma=160, Nullable=161, Include=162, IncludeAgain=163, DllLoad=164, 
		Requires=165, SingleInstance=166, Persistent=167, Warn=168, HookMutexName=169, 
		NoDynamicVars=170, ErrorStdOut=171, ClipboardTimeout=172, HotIfTimeout=173, 
		MaxThreads=174, MaxThreadsBuffer=175, MaxThreadsPerHotkey=176, WinActivateForce=177, 
		NoMainWindow=178, NoTrayIcon=179, Assembly=180, DirectiveHidden=181, ConditionalSymbol=182, 
		DirectiveSingleLineComment=183, DirectiveNewline=184, UnexpectedDirectiveCharacter=185, 
		DirectiveTextWhitespace=186, UnexpectedTextDirectiveCharacter=187, HotstringNewline=188, 
		NoMouse=189, EndChars=190, HotstringOptions=191;
	public const int
		RULE_preprocessor_directive = 0, RULE_directive_new_line_or_sharp = 1, 
		RULE_preprocessor_expression = 2;
	public static readonly string[] ruleNames = {
		"preprocessor_directive", "directive_new_line_or_sharp", "preprocessor_expression"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"'['", "']'", "'('", "')'", "'{'", "'}'", "','", "':='", "'?'", "'?.'", 
		"':'", "'::'", "'...'", "'.'", "'++'", "'--'", "'+'", "'-'", "'~'", "'!'", 
		"'*'", "'/'", "'//'", "'%'", "'**'", "'??'", "'#'", "'>>'", "'<<'", "'>>>'", 
		"'<'", "'>'", "'<='", "'>='", "'='", "'!='", "'=='", "'!=='", "'~='", 
		"'&'", "'^'", "'|'", "'&&'", "'||'", "'*='", "'/='", "'%='", "'+='", "'-='", 
		"'<<='", "'>>='", "'>>>='", "'//='", "'.='", "'&='", "'^='", "'|='", "'**='", 
		"'??='", "'=>'", "'null'", "'unset'", "'true'", "'false'", null, null, 
		null, null, null, null, null, null, null, "'break'", "'do'", "'instanceof'", 
		"'switch'", "'case'", "'default'", "'else'", "'catch'", "'finally'", "'return'", 
		"'continue'", "'for'", "'while'", "'parse'", "'reg'", "'read'", "'files'", 
		"'loop'", "'until'", "'this'", "'if'", "'throw'", "'delete'", "'in'", 
		"'try'", "'yield'", "'is'", "'contains'", "'and'", "'not'", "'or'", "'goto'", 
		"'get'", "'set'", "'class'", "'enum'", "'extends'", "'super'", "'base'", 
		"'export'", "'import'", "'from'", "'as'", "'async'", "'await'", "'static'", 
		"'global'", "'local'", null, null, null, null, null, null, null, null, 
		null, null, null, null, "'hotif'", "'inputlevel'", "'suspendexempt'", 
		"'usehook'", null, null, "'define'", "'undef'", "'elif'", "'endif'", "'line'", 
		null, null, null, null, null, null, null, null, null, null, null, "'persistent'", 
		null, null, "'nodynamicvars'", "'errorstdout'", "'clipboardtimeout'", 
		"'hotiftimeout'", "'maxthreads'", "'maxthreadsbuffer'", "'maxthreadsperhotkey'", 
		"'winactivateforce'", "'nomainwindow'", "'notrayicon'", null, "'hidden'", 
		null, null, null, null, null, null, null, "'NoMouse'", "'EndChars'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "DerefStart", "DerefEnd", "ObjectLiteralStart", "ObjectLiteralEnd", 
		"ConcatDot", "Maybe", "SingleLineBlockComment", "SingleLineComment", "HotstringTrigger", 
		"RemapKey", "HotkeyTrigger", "OpenBracket", "CloseBracket", "OpenParen", 
		"CloseParen", "OpenBrace", "CloseBrace", "Comma", "Assign", "QuestionMark", 
		"QuestionMarkDot", "Colon", "DoubleColon", "Ellipsis", "Dot", "PlusPlus", 
		"MinusMinus", "Plus", "Minus", "BitNot", "Not", "Multiply", "Divide", 
		"IntegerDivide", "Modulus", "Power", "NullCoalesce", "Hashtag", "RightShiftArithmetic", 
		"LeftShiftArithmetic", "RightShiftLogical", "LessThan", "MoreThan", "LessThanEquals", 
		"GreaterThanEquals", "Equals_", "NotEquals", "IdentityEquals", "IdentityNotEquals", 
		"RegExMatch", "BitAnd", "BitXOr", "BitOr", "And", "Or", "MultiplyAssign", 
		"DivideAssign", "ModulusAssign", "PlusAssign", "MinusAssign", "LeftShiftArithmeticAssign", 
		"RightShiftArithmeticAssign", "RightShiftLogicalAssign", "IntegerDivideAssign", 
		"ConcatenateAssign", "BitAndAssign", "BitXorAssign", "BitOrAssign", "PowerAssign", 
		"NullishCoalescingAssign", "Arrow", "NullLiteral", "Unset", "True", "False", 
		"DecimalLiteral", "HexIntegerLiteral", "OctalIntegerLiteral", "OctalIntegerLiteral2", 
		"BinaryIntegerLiteral", "BigHexIntegerLiteral", "BigOctalIntegerLiteral", 
		"BigBinaryIntegerLiteral", "BigDecimalIntegerLiteral", "Break", "Do", 
		"Instanceof", "Switch", "Case", "Default", "Else", "Catch", "Finally", 
		"Return", "Continue", "For", "While", "Parse", "Reg", "Read", "Files", 
		"Loop", "Until", "This", "If", "Throw", "Delete", "In", "Try", "Yield", 
		"Is", "Contains", "VerbalAnd", "VerbalNot", "VerbalOr", "Goto", "Get", 
		"Set", "Class", "Enum", "Extends", "Super", "Base", "Export", "Import", 
		"From", "As", "Async", "Await", "Static", "Global", "Local", "Identifier", 
		"ContinuationSection", "StringLiteral", "EOL", "WS", "UnexpectedCharacter", 
		"StringLiteralPart", "StringModeTerminator", "StringModeTrivia", "StringModeContinuationSection", 
		"HotstringExpansion", "Digits", "HotIf", "InputLevel", "SuspendExempt", 
		"UseHook", "Hotstring", "Module", "Define", "Undef", "ElIf", "EndIf", 
		"DirectiveLine", "Error", "Warning", "Region", "EndRegion", "Pragma", 
		"Nullable", "Include", "IncludeAgain", "DllLoad", "Requires", "SingleInstance", 
		"Persistent", "Warn", "HookMutexName", "NoDynamicVars", "ErrorStdOut", 
		"ClipboardTimeout", "HotIfTimeout", "MaxThreads", "MaxThreadsBuffer", 
		"MaxThreadsPerHotkey", "WinActivateForce", "NoMainWindow", "NoTrayIcon", 
		"Assembly", "DirectiveHidden", "ConditionalSymbol", "DirectiveSingleLineComment", 
		"DirectiveNewline", "UnexpectedDirectiveCharacter", "DirectiveTextWhitespace", 
		"UnexpectedTextDirectiveCharacter", "HotstringNewline", "NoMouse", "EndChars", 
		"HotstringOptions"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PreprocessorParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PreprocessorParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PreprocessorParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PreprocessorParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Preprocessor_directiveContext : ParserRuleContext {
		public Boolean value;
		public Preprocessor_directiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_directive; } }
	 
		public Preprocessor_directiveContext() { }
		public virtual void CopyFrom(Preprocessor_directiveContext context) {
			base.CopyFrom(context);
			this.value = context.value;
		}
	}
	public partial class PreprocessorNoTrayIconContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NoTrayIcon() { return GetToken(PreprocessorParser.NoTrayIcon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNoTrayIconContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNoTrayIcon(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNullableContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Nullable() { return GetToken(PreprocessorParser.Nullable, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNullableContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNullable(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorDeclarationContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Define() { return GetToken(PreprocessorParser.Define, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ConditionalSymbol() { return GetToken(PreprocessorParser.ConditionalSymbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Undef() { return GetToken(PreprocessorParser.Undef, 0); }
		public PreprocessorDeclarationContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorPragmaContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pragma() { return GetToken(PreprocessorParser.Pragma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorPragmaContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorPragma(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNoDynamicVarsContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NoDynamicVars() { return GetToken(PreprocessorParser.NoDynamicVars, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNoDynamicVarsContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNoDynamicVars(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorWinActivateForceContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WinActivateForce() { return GetToken(PreprocessorParser.WinActivateForce, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorWinActivateForceContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorWinActivateForce(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorLineContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DirectiveLine() { return GetToken(PreprocessorParser.DirectiveLine, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Default() { return GetToken(PreprocessorParser.Default, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DirectiveHidden() { return GetToken(PreprocessorParser.DirectiveHidden, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		public PreprocessorLineContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorLine(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNoMainWindowContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NoMainWindow() { return GetToken(PreprocessorParser.NoMainWindow, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorNoMainWindowContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNoMainWindow(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorTextualDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Include() { return GetToken(PreprocessorParser.Include, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IncludeAgain() { return GetToken(PreprocessorParser.IncludeAgain, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DllLoad() { return GetToken(PreprocessorParser.DllLoad, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Requires() { return GetToken(PreprocessorParser.Requires, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Assembly() { return GetToken(PreprocessorParser.Assembly, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HookMutexName() { return GetToken(PreprocessorParser.HookMutexName, 0); }
		public PreprocessorTextualDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorTextualDirective(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorPersistentContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Persistent() { return GetToken(PreprocessorParser.Persistent, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode True() { return GetToken(PreprocessorParser.True, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode False() { return GetToken(PreprocessorParser.False, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		public PreprocessorPersistentContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorPersistent(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorDiagnosticContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Error() { return GetToken(PreprocessorParser.Error, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Warning() { return GetToken(PreprocessorParser.Warning, 0); }
		public PreprocessorDiagnosticContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorDiagnostic(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorErrorStdOutContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ErrorStdOut() { return GetToken(PreprocessorParser.ErrorStdOut, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		public PreprocessorErrorStdOutContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorErrorStdOut(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorRegionContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Region() { return GetToken(PreprocessorParser.Region, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndRegion() { return GetToken(PreprocessorParser.EndRegion, 0); }
		public PreprocessorRegionContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorRegion(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorOptionalTextualDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Module() { return GetToken(PreprocessorParser.Module, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Warn() { return GetToken(PreprocessorParser.Warn, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SingleInstance() { return GetToken(PreprocessorParser.SingleInstance, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringLiteral() { return GetToken(PreprocessorParser.StringLiteral, 0); }
		public PreprocessorOptionalTextualDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorOptionalTextualDirective(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorConditionalContext : Preprocessor_directiveContext {
		public Preprocessor_expressionContext expr;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode If() { return GetToken(PreprocessorParser.If, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_expressionContext preprocessor_expression() {
			return GetRuleContext<Preprocessor_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ElIf() { return GetToken(PreprocessorParser.ElIf, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Else() { return GetToken(PreprocessorParser.Else, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EndIf() { return GetToken(PreprocessorParser.EndIf, 0); }
		public PreprocessorConditionalContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorConditional(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorNumericDirectiveContext : Preprocessor_directiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
			return GetRuleContext<Directive_new_line_or_sharpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HotIfTimeout() { return GetToken(PreprocessorParser.HotIfTimeout, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MaxThreads() { return GetToken(PreprocessorParser.MaxThreads, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MaxThreadsBuffer() { return GetToken(PreprocessorParser.MaxThreadsBuffer, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MaxThreadsPerHotkey() { return GetToken(PreprocessorParser.MaxThreadsPerHotkey, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ClipboardTimeout() { return GetToken(PreprocessorParser.ClipboardTimeout, 0); }
		public PreprocessorNumericDirectiveContext(Preprocessor_directiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorNumericDirective(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_directiveContext preprocessor_directive() {
		Preprocessor_directiveContext _localctx = new Preprocessor_directiveContext(Context, State);
		EnterRule(_localctx, 0, RULE_preprocessor_directive);
		int _la;
		try {
			State = 106;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Define:
				_localctx = new PreprocessorDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 6;
				Match(Define);
				State = 7;
				Match(ConditionalSymbol);
				State = 8;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveDefine(); 
				}
				break;
			case Undef:
				_localctx = new PreprocessorDeclarationContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 11;
				Match(Undef);
				State = 12;
				Match(ConditionalSymbol);
				State = 13;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveUndef(); 
				}
				break;
			case If:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 16;
				Match(If);
				State = 17;
				((PreprocessorConditionalContext)_localctx).expr = preprocessor_expression(0);
				State = 18;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveIf(); 
				}
				break;
			case ElIf:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 21;
				Match(ElIf);
				State = 22;
				((PreprocessorConditionalContext)_localctx).expr = preprocessor_expression(0);
				State = 23;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveElif(); 
				}
				break;
			case Else:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 26;
				Match(Else);
				State = 27;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveElse(); 
				}
				break;
			case EndIf:
				_localctx = new PreprocessorConditionalContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 30;
				Match(EndIf);
				State = 31;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveEndif(); 
				}
				break;
			case DirectiveLine:
				_localctx = new PreprocessorLineContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 34;
				Match(DirectiveLine);
				State = 41;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case Digits:
					{
					State = 35;
					Match(Digits);
					State = 37;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==StringLiteral) {
						{
						State = 36;
						Match(StringLiteral);
						}
					}

					}
					break;
				case Default:
					{
					State = 39;
					Match(Default);
					}
					break;
				case DirectiveHidden:
					{
					State = 40;
					Match(DirectiveHidden);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 43;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveLine(); 
				}
				break;
			case Error:
				_localctx = new PreprocessorDiagnosticContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 46;
				Match(Error);
				State = 47;
				Match(StringLiteral);
				State = 48;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveError(); 
				}
				break;
			case Warning:
				_localctx = new PreprocessorDiagnosticContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 51;
				Match(Warning);
				State = 52;
				Match(StringLiteral);
				State = 53;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveWarning(); 
				}
				break;
			case Region:
				_localctx = new PreprocessorRegionContext(_localctx);
				EnterOuterAlt(_localctx, 10);
				{
				State = 56;
				Match(Region);
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==StringLiteral) {
					{
					State = 57;
					Match(StringLiteral);
					}
				}

				State = 60;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveRegion(); 
				}
				break;
			case EndRegion:
				_localctx = new PreprocessorRegionContext(_localctx);
				EnterOuterAlt(_localctx, 11);
				{
				State = 63;
				Match(EndRegion);
				State = 65;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==StringLiteral) {
					{
					State = 64;
					Match(StringLiteral);
					}
				}

				State = 67;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveEndregion(); 
				}
				break;
			case Pragma:
				_localctx = new PreprocessorPragmaContext(_localctx);
				EnterOuterAlt(_localctx, 12);
				{
				State = 70;
				Match(Pragma);
				State = 71;
				Match(StringLiteral);
				State = 72;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectivePragma(); 
				}
				break;
			case Nullable:
				_localctx = new PreprocessorNullableContext(_localctx);
				EnterOuterAlt(_localctx, 13);
				{
				State = 75;
				Match(Nullable);
				State = 76;
				Match(StringLiteral);
				State = 77;
				directive_new_line_or_sharp();
				 this.OnPreprocessorDirectiveNullable(); 
				}
				break;
			case Include:
			case IncludeAgain:
			case DllLoad:
			case Requires:
			case HookMutexName:
			case Assembly:
				_localctx = new PreprocessorTextualDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 14);
				{
				State = 80;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 162)) & ~0x3f) == 0 && ((1L << (_la - 162)) & 262287L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 81;
				Match(StringLiteral);
				State = 82;
				directive_new_line_or_sharp();
				}
				break;
			case Persistent:
				_localctx = new PreprocessorPersistentContext(_localctx);
				EnterOuterAlt(_localctx, 15);
				{
				State = 83;
				Match(Persistent);
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==True || _la==False || _la==Digits) {
					{
					State = 84;
					_la = TokenStream.LA(1);
					if ( !(_la==True || _la==False || _la==Digits) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 87;
				directive_new_line_or_sharp();
				}
				break;
			case Module:
			case SingleInstance:
			case Warn:
				_localctx = new PreprocessorOptionalTextualDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 16);
				{
				State = 88;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 150)) & ~0x3f) == 0 && ((1L << (_la - 150)) & 327681L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==StringLiteral) {
					{
					State = 89;
					Match(StringLiteral);
					}
				}

				State = 92;
				directive_new_line_or_sharp();
				}
				break;
			case NoDynamicVars:
				_localctx = new PreprocessorNoDynamicVarsContext(_localctx);
				EnterOuterAlt(_localctx, 17);
				{
				State = 93;
				Match(NoDynamicVars);
				State = 94;
				directive_new_line_or_sharp();
				}
				break;
			case ErrorStdOut:
				_localctx = new PreprocessorErrorStdOutContext(_localctx);
				EnterOuterAlt(_localctx, 18);
				{
				State = 95;
				Match(ErrorStdOut);
				State = 96;
				directive_new_line_or_sharp();
				}
				break;
			case WinActivateForce:
				_localctx = new PreprocessorWinActivateForceContext(_localctx);
				EnterOuterAlt(_localctx, 19);
				{
				State = 97;
				Match(WinActivateForce);
				State = 98;
				directive_new_line_or_sharp();
				}
				break;
			case NoTrayIcon:
				_localctx = new PreprocessorNoTrayIconContext(_localctx);
				EnterOuterAlt(_localctx, 20);
				{
				State = 99;
				Match(NoTrayIcon);
				State = 100;
				directive_new_line_or_sharp();
				}
				break;
			case NoMainWindow:
				_localctx = new PreprocessorNoMainWindowContext(_localctx);
				EnterOuterAlt(_localctx, 21);
				{
				State = 101;
				Match(NoMainWindow);
				State = 102;
				directive_new_line_or_sharp();
				}
				break;
			case ClipboardTimeout:
			case HotIfTimeout:
			case MaxThreads:
			case MaxThreadsBuffer:
			case MaxThreadsPerHotkey:
				_localctx = new PreprocessorNumericDirectiveContext(_localctx);
				EnterOuterAlt(_localctx, 22);
				{
				State = 103;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 172)) & ~0x3f) == 0 && ((1L << (_la - 172)) & 31L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 104;
				Match(Digits);
				State = 105;
				directive_new_line_or_sharp();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Directive_new_line_or_sharpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DirectiveNewline() { return GetToken(PreprocessorParser.DirectiveNewline, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PreprocessorParser.Eof, 0); }
		public Directive_new_line_or_sharpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directive_new_line_or_sharp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDirective_new_line_or_sharp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Directive_new_line_or_sharpContext directive_new_line_or_sharp() {
		Directive_new_line_or_sharpContext _localctx = new Directive_new_line_or_sharpContext(Context, State);
		EnterRule(_localctx, 2, RULE_directive_new_line_or_sharp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==DirectiveNewline) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_expressionContext : ParserRuleContext {
		public String value;
		public Preprocessor_expressionContext expr1;
		public Preprocessor_expressionContext expr;
		public Preprocessor_expressionContext expr2;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode True() { return GetToken(PreprocessorParser.True, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode False() { return GetToken(PreprocessorParser.False, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Digits() { return GetToken(PreprocessorParser.Digits, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ConditionalSymbol() { return GetToken(PreprocessorParser.ConditionalSymbol, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OpenParen() { return GetToken(PreprocessorParser.OpenParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CloseParen() { return GetToken(PreprocessorParser.CloseParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_expressionContext[] preprocessor_expression() {
			return GetRuleContexts<Preprocessor_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_expressionContext preprocessor_expression(int i) {
			return GetRuleContext<Preprocessor_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Not() { return GetToken(PreprocessorParser.Not, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IdentityEquals() { return GetToken(PreprocessorParser.IdentityEquals, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NotEquals() { return GetToken(PreprocessorParser.NotEquals, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(PreprocessorParser.And, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Or() { return GetToken(PreprocessorParser.Or, 0); }
		public Preprocessor_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPreprocessorParserVisitor<TResult> typedVisitor = visitor as IPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessor_expression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_expressionContext preprocessor_expression() {
		return preprocessor_expression(0);
	}

	private Preprocessor_expressionContext preprocessor_expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Preprocessor_expressionContext _localctx = new Preprocessor_expressionContext(Context, _parentState);
		Preprocessor_expressionContext _prevctx = _localctx;
		int _startState = 4;
		EnterRecursionRule(_localctx, 4, RULE_preprocessor_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case True:
				{
				State = 111;
				Match(True);
				 this.OnPreprocessorExpressionTrue(); 
				}
				break;
			case False:
				{
				State = 113;
				Match(False);
				 this.OnPreprocessorExpressionFalse(); 
				}
				break;
			case Digits:
				{
				State = 115;
				Match(Digits);
				 this.OnPreprocessorExpressionDigits(); 
				}
				break;
			case ConditionalSymbol:
				{
				State = 117;
				Match(ConditionalSymbol);
				 this.OnPreprocessorExpressionConditionalSymbol(); 
				}
				break;
			case OpenParen:
				{
				State = 119;
				Match(OpenParen);
				State = 120;
				_localctx.expr = preprocessor_expression(0);
				State = 121;
				Match(CloseParen);
				 this.OnPreprocessorExpressionConditionalOpenParens(); 
				}
				break;
			case Not:
				{
				State = 124;
				Match(Not);
				State = 125;
				_localctx.expr = preprocessor_expression(5);
				 this.OnPreprocessorExpressionConditionalNot(); 
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 152;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 150;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
					case 1:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 130;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 131;
						Match(IdentityEquals);
						State = 132;
						_localctx.expr2 = preprocessor_expression(5);
						 this.OnPreprocessorExpressionConditionalEq(); 
						}
						break;
					case 2:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 135;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 136;
						Match(NotEquals);
						State = 137;
						_localctx.expr2 = preprocessor_expression(4);
						 this.OnPreprocessorExpressionConditionalNe(); 
						}
						break;
					case 3:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 140;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 141;
						Match(And);
						State = 142;
						_localctx.expr2 = preprocessor_expression(3);
						 this.OnPreprocessorExpressionConditionalAnd(); 
						}
						break;
					case 4:
						{
						_localctx = new Preprocessor_expressionContext(_parentctx, _parentState);
						_localctx.expr1 = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_preprocessor_expression);
						State = 145;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 146;
						Match(Or);
						State = 147;
						_localctx.expr2 = preprocessor_expression(2);
						 this.OnPreprocessorExpressionConditionalOr(); 
						}
						break;
					}
					} 
				}
				State = 154;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 2: return preprocessor_expression_sempred((Preprocessor_expressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool preprocessor_expression_sempred(Preprocessor_expressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,191,156,2,0,7,0,2,1,7,1,2,2,7,2,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
		0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,3,0,38,8,0,1,0,1,0,3,0,42,8,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,3,0,59,8,0,1,0,1,0,1,0,1,0,1,0,
		3,0,66,8,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,3,0,86,8,0,1,0,1,0,1,0,3,0,91,8,0,1,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,3,0,107,8,0,1,1,1,1,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,129,8,2,1,2,
		1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
		2,1,2,5,2,151,8,2,10,2,12,2,154,9,2,1,2,0,1,4,3,0,2,4,0,5,3,0,162,165,
		169,169,180,180,2,0,74,75,144,144,3,0,150,150,166,166,168,168,1,0,172,
		176,1,1,184,184,189,0,106,1,0,0,0,2,108,1,0,0,0,4,128,1,0,0,0,6,7,5,151,
		0,0,7,8,5,182,0,0,8,9,3,2,1,0,9,10,6,0,-1,0,10,107,1,0,0,0,11,12,5,152,
		0,0,12,13,5,182,0,0,13,14,3,2,1,0,14,15,6,0,-1,0,15,107,1,0,0,0,16,17,
		5,105,0,0,17,18,3,4,2,0,18,19,3,2,1,0,19,20,6,0,-1,0,20,107,1,0,0,0,21,
		22,5,153,0,0,22,23,3,4,2,0,23,24,3,2,1,0,24,25,6,0,-1,0,25,107,1,0,0,0,
		26,27,5,91,0,0,27,28,3,2,1,0,28,29,6,0,-1,0,29,107,1,0,0,0,30,31,5,154,
		0,0,31,32,3,2,1,0,32,33,6,0,-1,0,33,107,1,0,0,0,34,41,5,155,0,0,35,37,
		5,144,0,0,36,38,5,135,0,0,37,36,1,0,0,0,37,38,1,0,0,0,38,42,1,0,0,0,39,
		42,5,90,0,0,40,42,5,181,0,0,41,35,1,0,0,0,41,39,1,0,0,0,41,40,1,0,0,0,
		42,43,1,0,0,0,43,44,3,2,1,0,44,45,6,0,-1,0,45,107,1,0,0,0,46,47,5,156,
		0,0,47,48,5,135,0,0,48,49,3,2,1,0,49,50,6,0,-1,0,50,107,1,0,0,0,51,52,
		5,157,0,0,52,53,5,135,0,0,53,54,3,2,1,0,54,55,6,0,-1,0,55,107,1,0,0,0,
		56,58,5,158,0,0,57,59,5,135,0,0,58,57,1,0,0,0,58,59,1,0,0,0,59,60,1,0,
		0,0,60,61,3,2,1,0,61,62,6,0,-1,0,62,107,1,0,0,0,63,65,5,159,0,0,64,66,
		5,135,0,0,65,64,1,0,0,0,65,66,1,0,0,0,66,67,1,0,0,0,67,68,3,2,1,0,68,69,
		6,0,-1,0,69,107,1,0,0,0,70,71,5,160,0,0,71,72,5,135,0,0,72,73,3,2,1,0,
		73,74,6,0,-1,0,74,107,1,0,0,0,75,76,5,161,0,0,76,77,5,135,0,0,77,78,3,
		2,1,0,78,79,6,0,-1,0,79,107,1,0,0,0,80,81,7,0,0,0,81,82,5,135,0,0,82,107,
		3,2,1,0,83,85,5,167,0,0,84,86,7,1,0,0,85,84,1,0,0,0,85,86,1,0,0,0,86,87,
		1,0,0,0,87,107,3,2,1,0,88,90,7,2,0,0,89,91,5,135,0,0,90,89,1,0,0,0,90,
		91,1,0,0,0,91,92,1,0,0,0,92,107,3,2,1,0,93,94,5,170,0,0,94,107,3,2,1,0,
		95,96,5,171,0,0,96,107,3,2,1,0,97,98,5,177,0,0,98,107,3,2,1,0,99,100,5,
		179,0,0,100,107,3,2,1,0,101,102,5,178,0,0,102,107,3,2,1,0,103,104,7,3,
		0,0,104,105,5,144,0,0,105,107,3,2,1,0,106,6,1,0,0,0,106,11,1,0,0,0,106,
		16,1,0,0,0,106,21,1,0,0,0,106,26,1,0,0,0,106,30,1,0,0,0,106,34,1,0,0,0,
		106,46,1,0,0,0,106,51,1,0,0,0,106,56,1,0,0,0,106,63,1,0,0,0,106,70,1,0,
		0,0,106,75,1,0,0,0,106,80,1,0,0,0,106,83,1,0,0,0,106,88,1,0,0,0,106,93,
		1,0,0,0,106,95,1,0,0,0,106,97,1,0,0,0,106,99,1,0,0,0,106,101,1,0,0,0,106,
		103,1,0,0,0,107,1,1,0,0,0,108,109,7,4,0,0,109,3,1,0,0,0,110,111,6,2,-1,
		0,111,112,5,74,0,0,112,129,6,2,-1,0,113,114,5,75,0,0,114,129,6,2,-1,0,
		115,116,5,144,0,0,116,129,6,2,-1,0,117,118,5,182,0,0,118,129,6,2,-1,0,
		119,120,5,14,0,0,120,121,3,4,2,0,121,122,5,15,0,0,122,123,6,2,-1,0,123,
		129,1,0,0,0,124,125,5,31,0,0,125,126,3,4,2,5,126,127,6,2,-1,0,127,129,
		1,0,0,0,128,110,1,0,0,0,128,113,1,0,0,0,128,115,1,0,0,0,128,117,1,0,0,
		0,128,119,1,0,0,0,128,124,1,0,0,0,129,152,1,0,0,0,130,131,10,4,0,0,131,
		132,5,48,0,0,132,133,3,4,2,5,133,134,6,2,-1,0,134,151,1,0,0,0,135,136,
		10,3,0,0,136,137,5,47,0,0,137,138,3,4,2,4,138,139,6,2,-1,0,139,151,1,0,
		0,0,140,141,10,2,0,0,141,142,5,54,0,0,142,143,3,4,2,3,143,144,6,2,-1,0,
		144,151,1,0,0,0,145,146,10,1,0,0,146,147,5,55,0,0,147,148,3,4,2,2,148,
		149,6,2,-1,0,149,151,1,0,0,0,150,130,1,0,0,0,150,135,1,0,0,0,150,140,1,
		0,0,0,150,145,1,0,0,0,151,154,1,0,0,0,152,150,1,0,0,0,152,153,1,0,0,0,
		153,5,1,0,0,0,154,152,1,0,0,0,10,37,41,58,65,85,90,106,128,150,152
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
